system:
  host: 0.0.0.0
  port: 8080
  env: release
mysql:
  host: localhost # 数据库主机
  port: 3306              # 数据库端口
  config: charset=utf8mb4&parseTime=True&loc=Local # 数据库配置
  db: ccops          # 数据库名称
  user: root      # 数据库用户名
  password: 123456  # 数据库密码
  log_level: info         # 日志级别
logger:
  level: info
  prefix: '[ccops]'
  director: log
  show_line: true
  log_in_console: true
jwt:
  secret: xxx
  issuer: xx
  accessExpires  : 24
  refreshExpires : 720